[package]
name = "backlog"
description.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true

include = [
    "src/**/*.rs",
    "tests/**/*.rs",
    "LICENSE-*",
    "README.md",
    "src/sqlite/connection/diesel_manage_updated_at.sql",
    "src/migration/setup_migration_table.sql",
]

[dependencies]
